### ISSUE TITLE
Error when exceeding VPCs limit is unclear

### ISSUE THREAD

**Issue by yairbb** [QualiSystems/AWS-Shell#112]
In case that we have exceeded to the limit of VPC's, a general Error is obtained " VPC is not set to this reservation". A specific Error shall be obtained  something like : " The maximum number of VPCs has been reached"

**Comment by alexazarh** [comment]
I think the error in the issue description refers to the output from the deploy command when you try to execute it after setup has failed. During the deploy we dont create VPCs so we cant know that the vpc doesnt exist because we reached the limit. There can be other reasons as well to why the vpc is not found, like if someone deleted it manually or changed its name.
However, if you look at the output of the setup script you get a clear message that tells you that the VPC limit is reached:
![image](https://cloud.githubusercontent.com/assets/6730546/17670907/d3802b0a-631c-11e6-8aef-2aa6a1d55aa1.png)

So we can change the error message from the deploy: "VPC is not set for this reservation" but the suggested message is incorrect.
