### ISSUE TITLE
When running 50 apps in multiple reservation some of the apps (1-3 apps) in only one of the reservations will not deploy

### ISSUE THREAD

**Issue by tornizanQ** [QualiSystems/AWS-Shell#236]
STR
Have environment with 50 apps 
Reserve that environment 3 times 

BIR
**unstable**
Some of the apps are not being deployed

also occure with reservations of 30 apps but even less stable

logs
[QsDriverHost.exe.txt](https://github.com/QualiSystems/AWS-Shell/files/395242/QsDriverHost.exe.txt)

**Comment by alonagetzler** [comment]
according to the concurrency testing we can create up to 140 instances concurrently in the same AWS region (in one or multiple reservations). above this number we start hitting issues caused by AWS API. it is probably possible to overcome some of those issues but currently it is not a priority.  archiving this bug.
